spring:
  application:
    name: leadflow-backend

  datasource:
    url: jdbc:postgresql://localhost:2411/leadflow
    username: postgres
    password: venusia
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        multiTenancy: SCHEMA

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/global
      - classpath:db/migration/tenants
    schemas:
      - public
      - tenant_x

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    "[com.leadflow]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE

security:
  jwt:
    secret: "leadflow-super-secret-key-2026-ultra-secure"
    expiration: 3600000
  filter:
    order:
      tenantFilter: BEFORE UsernamePasswordAuthenticationFilter